\set ON_ERROR_STOP on

-- Generated by apply_role_model_update_v5.ps1
-- Drops only RLS POLICY objects recreated by the following source file.
-- This file does not delete table rows.

DROP POLICY IF EXISTS pol_storage_select ON collection.storage_locations;
DROP POLICY IF EXISTS pol_storage_modify ON collection.storage_locations;
DROP POLICY IF EXISTS pol_collection_entry_select ON collection.entries;
DROP POLICY IF EXISTS pol_collection_entry_modify ON collection.entries;
DROP POLICY IF EXISTS pol_collection_instance_select ON collection.instances;
DROP POLICY IF EXISTS pol_collection_instance_modify ON collection.instances;
DROP POLICY IF EXISTS pol_instance_adjustments_select ON collection.instance_adjustments;
DROP POLICY IF EXISTS pol_instance_adjustments_modify ON collection.instance_adjustments;
DROP POLICY IF EXISTS pol_storage_allocations_select ON collection.storage_allocations;
DROP POLICY IF EXISTS pol_storage_allocations_modify ON collection.storage_allocations;
DROP POLICY IF EXISTS pol_acquisitions_select ON collection.acquisitions;
DROP POLICY IF EXISTS pol_acquisitions_modify ON collection.acquisitions;
DROP POLICY IF EXISTS pol_acquisition_items_select ON collection.acquisition_items;
DROP POLICY IF EXISTS pol_acquisition_items_modify ON collection.acquisition_items;
DROP POLICY IF EXISTS pol_tags_select ON collection.tags;
DROP POLICY IF EXISTS pol_tags_modify ON collection.tags;
DROP POLICY IF EXISTS pol_entry_tags_select ON collection.entry_tags;
DROP POLICY IF EXISTS pol_entry_tags_modify ON collection.entry_tags;
DROP POLICY IF EXISTS pol_transfers_select ON collection.transfers;
DROP POLICY IF EXISTS pol_transfers_insert ON collection.transfers;
