\set ON_ERROR_STOP on

-- Generated by apply_role_model_update_v4.ps1
-- Drops only RLS POLICY objects recreated by the following source file.
-- This file does not delete table rows.

DROP POLICY IF EXISTS pol_credentials_manage ON identity.user_credentials;
DROP POLICY IF EXISTS pol_sessions_manage ON identity.user_sessions;
DROP POLICY IF EXISTS pol_tokens_manage ON identity.one_time_tokens;
