\set ON_ERROR_STOP on

-- Generated by apply_role_model_update_v4.ps1
-- Drops only RLS POLICY objects recreated by the following source file.
-- This file does not delete table rows.

DROP POLICY IF EXISTS pol_catalog_items_select ON catalog.items;
DROP POLICY IF EXISTS pol_catalog_sets_select ON catalog.sets;
DROP POLICY IF EXISTS pol_catalog_parts_select ON catalog.parts;
DROP POLICY IF EXISTS pol_catalog_minifigures_select ON catalog.minifigures;
DROP POLICY IF EXISTS pol_catalog_books_select ON catalog.books;
DROP POLICY IF EXISTS pol_catalog_moc_subtype_select ON catalog.mocs;
DROP POLICY IF EXISTS pol_catalog_sticker_sheets_select ON catalog.sticker_sheets;
DROP POLICY IF EXISTS pol_catalog_instructions_select ON catalog.instructions;
DROP POLICY IF EXISTS pol_catalog_packaging_select ON catalog.packaging;
DROP POLICY IF EXISTS pol_catalog_gear_select ON catalog.gear;
DROP POLICY IF EXISTS pol_catalog_accessories_select ON catalog.accessories;
DROP POLICY IF EXISTS pol_catalog_polybags_select ON catalog.polybags;
DROP POLICY IF EXISTS pol_catalog_promotional_items_select ON catalog.promotional_items;
DROP POLICY IF EXISTS pol_catalog_publications_select ON catalog.publications;
DROP POLICY IF EXISTS pol_catalog_other_items_select ON catalog.other_items;
DROP POLICY IF EXISTS pol_part_variants_select ON catalog.part_variants;
DROP POLICY IF EXISTS pol_lego_elements_select ON catalog.lego_elements;
DROP POLICY IF EXISTS pol_external_identifiers_select ON catalog.external_identifiers;
DROP POLICY IF EXISTS pol_source_values_select ON catalog.source_values;
DROP POLICY IF EXISTS pol_source_value_history_select ON catalog.source_value_history;
DROP POLICY IF EXISTS pol_admin_overrides_select ON catalog.admin_overrides;
DROP POLICY IF EXISTS pol_inventory_definitions_select ON definition.inventory_definitions;
DROP POLICY IF EXISTS pol_inventory_versions_select ON definition.inventory_versions;
DROP POLICY IF EXISTS pol_requirement_groups_select ON definition.requirement_groups;
DROP POLICY IF EXISTS pol_requirement_options_select ON definition.requirement_options;
DROP POLICY IF EXISTS pol_definition_authority_select ON definition.definition_authority;
DROP POLICY IF EXISTS pol_part_molds_select ON catalog.part_molds;
DROP POLICY IF EXISTS pol_part_mold_revisions_select ON catalog.part_mold_revisions;
DROP POLICY IF EXISTS pol_part_mold_substitutions_select ON catalog.part_mold_substitutions;
DROP POLICY IF EXISTS pol_decorated_variants_select ON catalog.decorated_variants;
DROP POLICY IF EXISTS pol_item_barcodes_select ON catalog.item_barcodes;
DROP POLICY IF EXISTS pol_item_images_select ON catalog.item_images;
DROP POLICY IF EXISTS pol_item_relationships_select ON catalog.item_relationships;
DROP POLICY IF EXISTS pol_instruction_assets_select ON catalog.instruction_assets;
DROP POLICY IF EXISTS pol_item_search_select ON catalog.item_search;
DROP POLICY IF EXISTS pol_manifest_subassemblies_select ON definition.manifest_subassemblies;
DROP POLICY IF EXISTS pol_manifest_requirement_placements_select ON definition.manifest_requirement_placements;
DROP POLICY IF EXISTS pol_minifig_compositions_select ON definition.minifig_compositions;
DROP POLICY IF EXISTS pol_minifig_structural_components_select ON definition.minifig_structural_components;
DROP POLICY IF EXISTS pol_minifig_accessories_select ON definition.minifig_accessories;
