\set ON_ERROR_STOP on

-- Generated by apply_role_model_update_v2.ps1
-- Drops only RLS policy objects that the following source file recreates.
-- No table rows are deleted.

DROP POLICY IF EXISTS pol_mocs_select ON moc.mocs;
DROP POLICY IF EXISTS pol_mocs_modify ON moc.mocs;
DROP POLICY IF EXISTS pol_moc_revisions_select ON moc.revisions;
DROP POLICY IF EXISTS pol_moc_revisions_modify ON moc.revisions;
DROP POLICY IF EXISTS pol_moc_subassemblies_select ON moc.subassemblies;
DROP POLICY IF EXISTS pol_moc_subassemblies_modify ON moc.subassemblies;
DROP POLICY IF EXISTS pol_moc_licenses_select ON moc.licenses;
DROP POLICY IF EXISTS pol_moc_licenses_modify ON moc.licenses;
DROP POLICY IF EXISTS pol_moc_assets_select ON moc.assets;
DROP POLICY IF EXISTS pol_moc_assets_modify ON moc.assets;
DROP POLICY IF EXISTS pol_moc_forks_select ON moc.forks;
DROP POLICY IF EXISTS pol_moc_forks_modify ON moc.forks;
