\set ON_ERROR_STOP on

-- Generated by apply_role_model_update_v2.ps1
-- Drops only RLS policy objects that the following source file recreates.
-- No table rows are deleted.

DROP POLICY IF EXISTS audit_events_owner_insert ON audit.events;
DROP POLICY IF EXISTS audit_events_owner_select ON audit.events;
DROP POLICY IF EXISTS audit_changes_owner_insert ON audit.changes;
DROP POLICY IF EXISTS audit_changes_owner_select ON audit.changes;
