\set ON_ERROR_STOP on

-- Generated by apply_role_model_update_v2.ps1
-- Drops only RLS policy objects that the following source file recreates.
-- No table rows are deleted.

DROP POLICY IF EXISTS pol_import_jobs_select ON import.jobs;
DROP POLICY IF EXISTS pol_import_jobs_modify ON import.jobs;
DROP POLICY IF EXISTS pol_raw_records_select ON import.raw_records;
DROP POLICY IF EXISTS pol_raw_records_modify ON import.raw_records;
DROP POLICY IF EXISTS pol_normalized_records_select ON import.normalized_records;
DROP POLICY IF EXISTS pol_normalized_records_modify ON import.normalized_records;
DROP POLICY IF EXISTS pol_matches_select ON import.matches;
DROP POLICY IF EXISTS pol_matches_modify ON import.matches;
DROP POLICY IF EXISTS pol_user_mapping_suggestions_self ON import.user_mapping_suggestions;
DROP POLICY IF EXISTS pol_import_applications_select ON import.applications;
DROP POLICY IF EXISTS pol_import_applications_modify ON import.applications;
DROP POLICY IF EXISTS pol_application_changes_select ON import.application_changes;
DROP POLICY IF EXISTS pol_application_changes_modify ON import.application_changes;
