\set ON_ERROR_STOP on

-- Generated by apply_role_model_update_v2.ps1
-- Drops only RLS policy objects that the following source file recreates.
-- No table rows are deleted.

DROP POLICY IF EXISTS pol_marketplace_listings_select ON marketplace.listings;
DROP POLICY IF EXISTS pol_marketplace_listings_manage ON marketplace.listings;
DROP POLICY IF EXISTS pol_marketplace_orders_select ON marketplace.orders;
DROP POLICY IF EXISTS pol_marketplace_orders_manage ON marketplace.orders;
DROP POLICY IF EXISTS pol_notifications_self ON operations.notifications;
DROP POLICY IF EXISTS pol_marketplace_listing_items_select ON marketplace.listing_items;
DROP POLICY IF EXISTS pol_marketplace_listing_items_manage ON marketplace.listing_items;
DROP POLICY IF EXISTS pol_marketplace_order_items_select ON marketplace.order_items;
