\set ON_ERROR_STOP on

-- Generated by apply_role_model_update_v2.ps1
-- Drops only RLS policy objects that the following source file recreates.
-- No table rows are deleted.

DROP POLICY IF EXISTS pol_wishlists_select ON wanted.wishlists;
DROP POLICY IF EXISTS pol_wishlists_modify ON wanted.wishlists;
DROP POLICY IF EXISTS pol_wishlist_entries_select ON wanted.wishlist_entries;
DROP POLICY IF EXISTS pol_wishlist_entries_modify ON wanted.wishlist_entries;
DROP POLICY IF EXISTS pol_wishlist_reservations_reserver_select ON wanted.wishlist_reservations;
DROP POLICY IF EXISTS pol_wishlist_reservations_owner_visible_select ON wanted.wishlist_reservations;
DROP POLICY IF EXISTS pol_wishlist_reservations_reserver_modify ON wanted.wishlist_reservations;
DROP POLICY IF EXISTS pol_build_goals_select ON wanted.build_goals;
DROP POLICY IF EXISTS pol_build_goals_modify ON wanted.build_goals;
DROP POLICY IF EXISTS pol_build_allocations_select ON wanted.build_allocations;
DROP POLICY IF EXISTS pol_build_allocations_modify ON wanted.build_allocations;
