\set ON_ERROR_STOP on

-- Generated by apply_role_model_update_v2.ps1
-- Drops only RLS policy objects that the following source file recreates.
-- No table rows are deleted.

DROP POLICY IF EXISTS pol_credentials_manage ON identity.user_credentials;
DROP POLICY IF EXISTS pol_sessions_manage ON identity.user_sessions;
DROP POLICY IF EXISTS pol_tokens_manage ON identity.one_time_tokens;
