\set ON_ERROR_STOP on

-- Generated by apply_role_model_update_v3.ps1
-- Drops only RLS POLICY objects recreated by the following source file.
-- This file does not delete table rows.

DROP POLICY IF EXISTS audit_events_owner_insert ON audit.events;
DROP POLICY IF EXISTS audit_events_owner_select ON audit.events;
DROP POLICY IF EXISTS audit_changes_owner_insert ON audit.changes;
DROP POLICY IF EXISTS audit_changes_owner_select ON audit.changes;
